---
functional:
  - Пользователь должен иметь возможность успешно зарегистрироваться с помощью эллектронной почты
  - Пользователь должен иметь возможность успешно зарегистрироваться с помощью аккаунта Github или Discord
  - Пользователь должен иметь возможность сбросить пароль на своем аккаунте и создать новый
  - Пользователь должен иметь возможность успешно запустить пробную игру без регистрации на сайте
  - Пользователь должен иметь возможность успешно создать игру с ботом 
  - Пользователь должен иметь возможность успешно создать игру с случайным пользователем
  - Пользователь должен иметь возможность успешно создать игру с другом
  - Пользователь должен иметь возможность просматривать статистику о себе
  - Пользователь должен иметь возможность просматривать историю завершённых игр
  - Пользователь должен иметь возможность редактировать свой профиль
  - Пользователь должен иметь возможность просматривать рейтинг пользователей и фильтровать список
  - Пользователь должен иметь возможность создать турнир
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - При авторизации или регистрации в поле "Password" должна быть кнопка раскрытия для просмотра пароля
  - Пользователь должен иметь возможность приостановить игру при батле с ботом 
